name: CI

on:
  push:
    branches: ["main"]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      working-directory: ./webapp
      run: |
        npm install
        npm run build
      env:
        CI: false
        REACT_APP_API_SERVER_ADDR: ${{ secrets.REACT_APP_API_SERVER_ADDR }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        deploy_key: ${{ secrets.GH_ACTIONS_DEPLOY_KEY }}
        publish_branch: production/gh-pages
        publish_dir: ./webapp/build
